"""API endpoints for Artifact metadata, verification, and retrieval."""

from fastapi import APIRouter, Depends

from ..dependencies import get_execution_service
from ...services.execution_service import ExecutionService
from ..schemas.artifact import (
    ArtifactResponse,
    ArtifactContentResponse,
    ArtifactListResponse,
)

artifacts_router = APIRouter(prefix="/executions/{execution_id}/artifacts", tags=["Artifacts"])


import json
from ...domain.models.artifact import ArtifactType


@artifacts_router.get(
    "",
    response_model=ArtifactListResponse,
    summary="List artifacts generated by execution",
)
async def list_artifacts(
    execution_id: str,
    service: ExecutionService = Depends(get_execution_service),
) -> ArtifactListResponse:
    """Lists metadata for all artifacts generated by a specific workflow execution."""
    artifacts = await service.list_artifacts(execution_id)
    items = [
        ArtifactResponse(
            id=a.id,
            workflow_execution_id=a.workflow_execution_id,
            task_key=a.task_key,
            task_execution_id=None,
            artifact_name=a.name,
            artifact_type=a.artifact_type.value if hasattr(a.artifact_type, "value") else str(a.artifact_type),
            content_hash=a.checksum_sha256,
            size_bytes=len(a.content.encode("utf-8")),
            storage_uri=None,
            metadata=a.metadata,
            created_at=a.created_at,
        )
        for a in artifacts
    ]
    return ArtifactListResponse(items=items, total_count=len(items))


@artifacts_router.get(
    "/{artifact_id}",
    response_model=ArtifactContentResponse,
    summary="Retrieve artifact data with SHA-256 verification",
)
async def get_artifact(
    execution_id: str,
    artifact_id: str,
    service: ExecutionService = Depends(get_execution_service),
) -> ArtifactContentResponse:
    """Retrieves artifact payload, verifying cryptographic hash integrity before returning."""
    artifact, is_valid = await service.get_artifact(artifact_id)
    parsed_data = artifact.content
    if artifact.artifact_type == ArtifactType.JSON:
        try:
            parsed_data = json.loads(artifact.content)
        except Exception:
            parsed_data = artifact.content

    return ArtifactContentResponse(
        artifact_id=artifact.id,
        artifact_name=artifact.name,
        artifact_type=artifact.artifact_type.value if hasattr(artifact.artifact_type, "value") else str(artifact.artifact_type),
        content_hash=artifact.checksum_sha256,
        verified=is_valid,
        data=parsed_data,
    )
